// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: lobslaw/v1/lobslaw.proto

package lobslawv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Register_FullMethodName   = "/lobslaw.v1.NodeService/Register"
	NodeService_Deregister_FullMethodName = "/lobslaw.v1.NodeService/Deregister"
	NodeService_Heartbeat_FullMethodName  = "/lobslaw.v1.NodeService/Heartbeat"
	NodeService_GetPeers_FullMethodName   = "/lobslaw.v1.NodeService/GetPeers"
	NodeService_Reload_FullMethodName     = "/lobslaw.v1.NodeService/Reload"
	NodeService_AddMember_FullMethodName  = "/lobslaw.v1.NodeService/AddMember"
	NodeService_Propose_FullMethodName    = "/lobslaw.v1.NodeService/Propose"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error)
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error)
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error)
	// Propose applies one already-marshalled LogEntry on the Raft
	// leader, on behalf of a follower that received the write.
	//
	// Only the leader may write, but a user's message lands on
	// whichever gateway node they happened to reach, which is
	// uncorrelated with leadership. Without this a follower cannot
	// persist a conversation turn at all.
	//
	// Leader-only and non-forwarding by construction: a node that is
	// not the leader returns FAILED_PRECONDITION rather than passing
	// the entry on, so a forward is always exactly one hop and a
	// cycle is impossible.
	//
	// This grants a peer no authority it did not already have. The
	// Raft transport shares this gRPC server and the same cluster
	// mTLS identity, and it already accepts arbitrary log
	// replication — the trust boundary is cluster membership, not
	// this method.
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, NodeService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, NodeService_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, NodeService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeersResponse)
	err := c.cc.Invoke(ctx, NodeService_GetPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, NodeService_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMemberResponse)
	err := c.cc.Invoke(ctx, NodeService_AddMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, NodeService_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations should embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error)
	Reload(context.Context, *ReloadRequest) (*ReloadResponse, error)
	AddMember(context.Context, *AddMemberRequest) (*AddMemberResponse, error)
	// Propose applies one already-marshalled LogEntry on the Raft
	// leader, on behalf of a follower that received the write.
	//
	// Only the leader may write, but a user's message lands on
	// whichever gateway node they happened to reach, which is
	// uncorrelated with leadership. Without this a follower cannot
	// persist a conversation turn at all.
	//
	// Leader-only and non-forwarding by construction: a node that is
	// not the leader returns FAILED_PRECONDITION rather than passing
	// the entry on, so a forward is always exactly one hop and a
	// cycle is impossible.
	//
	// This grants a peer no authority it did not already have. The
	// Raft transport shares this gRPC server and the same cluster
	// mTLS identity, and it already accepts arbitrary log
	// replication — the trust boundary is cluster membership, not
	// this method.
	Propose(context.Context, *ProposeRequest) (*ProposeResponse, error)
}

// UnimplementedNodeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedNodeServiceServer) Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedNodeServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeServiceServer) GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedNodeServiceServer) Reload(context.Context, *ReloadRequest) (*ReloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedNodeServiceServer) AddMember(context.Context, *AddMemberRequest) (*AddMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMember not implemented")
}
func (UnimplementedNodeServiceServer) Propose(context.Context, *ProposeRequest) (*ProposeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedNodeServiceServer) testEmbeddedByValue() {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetPeers(ctx, req.(*GetPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_AddMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).AddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobslaw.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _NodeService_Register_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _NodeService_Deregister_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NodeService_Heartbeat_Handler,
		},
		{
			MethodName: "GetPeers",
			Handler:    _NodeService_GetPeers_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _NodeService_Reload_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _NodeService_AddMember_Handler,
		},
		{
			MethodName: "Propose",
			Handler:    _NodeService_Propose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobslaw/v1/lobslaw.proto",
}

const (
	SkillService_ImportSkill_FullMethodName   = "/lobslaw.v1.SkillService/ImportSkill"
	SkillService_ExportSkill_FullMethodName   = "/lobslaw.v1.SkillService/ExportSkill"
	SkillService_ListSkills_FullMethodName    = "/lobslaw.v1.SkillService/ListSkills"
	SkillService_RemoveSkill_FullMethodName   = "/lobslaw.v1.SkillService/RemoveSkill"
	SkillService_ActivateSkill_FullMethodName = "/lobslaw.v1.SkillService/ActivateSkill"
)

// SkillServiceClient is the client API for SkillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -----------------------------------------------------------------------------
// SkillService — install, inspect and remove skills on a RUNNING cluster
// -----------------------------------------------------------------------------
//
// The BYTES travel, not a path. `lobslaw skills import` runs on
// somebody's laptop and the cluster is elsewhere, so a service taking a
// directory would be reading one that does not exist on the node.
type SkillServiceClient interface {
	ImportSkill(ctx context.Context, in *ImportSkillRequest, opts ...grpc.CallOption) (*ImportSkillResponse, error)
	ExportSkill(ctx context.Context, in *ExportSkillRequest, opts ...grpc.CallOption) (*ExportSkillResponse, error)
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error)
	RemoveSkill(ctx context.Context, in *RemoveSkillRequest, opts ...grpc.CallOption) (*RemoveSkillResponse, error)
	// ActivateSkill makes a stored version the one in force. This is
	// what `lobslaw skills rollback` calls — a rollback is nothing more
	// than activating a version that is already in the log.
	ActivateSkill(ctx context.Context, in *ActivateSkillRequest, opts ...grpc.CallOption) (*ActivateSkillResponse, error)
}

type skillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillServiceClient(cc grpc.ClientConnInterface) SkillServiceClient {
	return &skillServiceClient{cc}
}

func (c *skillServiceClient) ImportSkill(ctx context.Context, in *ImportSkillRequest, opts ...grpc.CallOption) (*ImportSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportSkillResponse)
	err := c.cc.Invoke(ctx, SkillService_ImportSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ExportSkill(ctx context.Context, in *ExportSkillRequest, opts ...grpc.CallOption) (*ExportSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSkillResponse)
	err := c.cc.Invoke(ctx, SkillService_ExportSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsResponse)
	err := c.cc.Invoke(ctx, SkillService_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) RemoveSkill(ctx context.Context, in *RemoveSkillRequest, opts ...grpc.CallOption) (*RemoveSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSkillResponse)
	err := c.cc.Invoke(ctx, SkillService_RemoveSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ActivateSkill(ctx context.Context, in *ActivateSkillRequest, opts ...grpc.CallOption) (*ActivateSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateSkillResponse)
	err := c.cc.Invoke(ctx, SkillService_ActivateSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillServiceServer is the server API for SkillService service.
// All implementations should embed UnimplementedSkillServiceServer
// for forward compatibility.
//
// -----------------------------------------------------------------------------
// SkillService — install, inspect and remove skills on a RUNNING cluster
// -----------------------------------------------------------------------------
//
// The BYTES travel, not a path. `lobslaw skills import` runs on
// somebody's laptop and the cluster is elsewhere, so a service taking a
// directory would be reading one that does not exist on the node.
type SkillServiceServer interface {
	ImportSkill(context.Context, *ImportSkillRequest) (*ImportSkillResponse, error)
	ExportSkill(context.Context, *ExportSkillRequest) (*ExportSkillResponse, error)
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	RemoveSkill(context.Context, *RemoveSkillRequest) (*RemoveSkillResponse, error)
	// ActivateSkill makes a stored version the one in force. This is
	// what `lobslaw skills rollback` calls — a rollback is nothing more
	// than activating a version that is already in the log.
	ActivateSkill(context.Context, *ActivateSkillRequest) (*ActivateSkillResponse, error)
}

// UnimplementedSkillServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkillServiceServer struct{}

func (UnimplementedSkillServiceServer) ImportSkill(context.Context, *ImportSkillRequest) (*ImportSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSkill not implemented")
}
func (UnimplementedSkillServiceServer) ExportSkill(context.Context, *ExportSkillRequest) (*ExportSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportSkill not implemented")
}
func (UnimplementedSkillServiceServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedSkillServiceServer) RemoveSkill(context.Context, *RemoveSkillRequest) (*RemoveSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSkill not implemented")
}
func (UnimplementedSkillServiceServer) ActivateSkill(context.Context, *ActivateSkillRequest) (*ActivateSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateSkill not implemented")
}
func (UnimplementedSkillServiceServer) testEmbeddedByValue() {}

// UnsafeSkillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkillServiceServer will
// result in compilation errors.
type UnsafeSkillServiceServer interface {
	mustEmbedUnimplementedSkillServiceServer()
}

func RegisterSkillServiceServer(s grpc.ServiceRegistrar, srv SkillServiceServer) {
	// If the following call pancis, it indicates UnimplementedSkillServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkillService_ServiceDesc, srv)
}

func _SkillService_ImportSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ImportSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ImportSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ImportSkill(ctx, req.(*ImportSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ExportSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ExportSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ExportSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ExportSkill(ctx, req.(*ExportSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_RemoveSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).RemoveSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_RemoveSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).RemoveSkill(ctx, req.(*RemoveSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ActivateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ActivateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ActivateSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ActivateSkill(ctx, req.(*ActivateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkillService_ServiceDesc is the grpc.ServiceDesc for SkillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobslaw.v1.SkillService",
	HandlerType: (*SkillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImportSkill",
			Handler:    _SkillService_ImportSkill_Handler,
		},
		{
			MethodName: "ExportSkill",
			Handler:    _SkillService_ExportSkill_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _SkillService_ListSkills_Handler,
		},
		{
			MethodName: "RemoveSkill",
			Handler:    _SkillService_RemoveSkill_Handler,
		},
		{
			MethodName: "ActivateSkill",
			Handler:    _SkillService_ActivateSkill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobslaw/v1/lobslaw.proto",
}

const (
	SelfLearningService_ListArtefacts_FullMethodName   = "/lobslaw.v1.SelfLearningService/ListArtefacts"
	SelfLearningService_ApproveArtefact_FullMethodName = "/lobslaw.v1.SelfLearningService/ApproveArtefact"
	SelfLearningService_DecideRevision_FullMethodName  = "/lobslaw.v1.SelfLearningService/DecideRevision"
	SelfLearningService_ArchiveArtefact_FullMethodName = "/lobslaw.v1.SelfLearningService/ArchiveArtefact"
	SelfLearningService_RestoreArtefact_FullMethodName = "/lobslaw.v1.SelfLearningService/RestoreArtefact"
)

// SelfLearningServiceClient is the client API for SelfLearningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -----------------------------------------------------------------------------
// SelfLearningService — inspect and decide on what the agent taught itself
// -----------------------------------------------------------------------------
//
// The offline `lobslaw learned` CLI opens state.db directly, which
// means bbolt's exclusive lock, which means the node must be stopped.
// That is a fine shape for forensics and a terrible one for approval:
// approving a proposal is a routine act, and requiring a service
// outage to perform it guarantees that nobody does it — after which
// propose mode is a queue that only fills.
//
// So the same operations are reachable on a RUNNING cluster. Writes
// forward to the leader like every other write; the offline CLI stays
// for the case where the node will not start.
//
// Deliberately NOT reachable from a conversation. Approval is the act
// that decides whether the agent's own suggestion becomes something it
// follows, and routing it through the channel the agent writes in puts
// the request and the approval on the same wire. The in-channel path
// is a later, separate decision, and it will sit on the durable
// confirmation records rather than on this service.
type SelfLearningServiceClient interface {
	ListArtefacts(ctx context.Context, in *ListArtefactsRequest, opts ...grpc.CallOption) (*ListArtefactsResponse, error)
	ApproveArtefact(ctx context.Context, in *ApproveArtefactRequest, opts ...grpc.CallOption) (*ApproveArtefactResponse, error)
	DecideRevision(ctx context.Context, in *DecideRevisionRequest, opts ...grpc.CallOption) (*DecideRevisionResponse, error)
	ArchiveArtefact(ctx context.Context, in *ArchiveArtefactRequest, opts ...grpc.CallOption) (*ArchiveArtefactResponse, error)
	RestoreArtefact(ctx context.Context, in *RestoreArtefactRequest, opts ...grpc.CallOption) (*RestoreArtefactResponse, error)
}

type selfLearningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSelfLearningServiceClient(cc grpc.ClientConnInterface) SelfLearningServiceClient {
	return &selfLearningServiceClient{cc}
}

func (c *selfLearningServiceClient) ListArtefacts(ctx context.Context, in *ListArtefactsRequest, opts ...grpc.CallOption) (*ListArtefactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArtefactsResponse)
	err := c.cc.Invoke(ctx, SelfLearningService_ListArtefacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selfLearningServiceClient) ApproveArtefact(ctx context.Context, in *ApproveArtefactRequest, opts ...grpc.CallOption) (*ApproveArtefactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveArtefactResponse)
	err := c.cc.Invoke(ctx, SelfLearningService_ApproveArtefact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selfLearningServiceClient) DecideRevision(ctx context.Context, in *DecideRevisionRequest, opts ...grpc.CallOption) (*DecideRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecideRevisionResponse)
	err := c.cc.Invoke(ctx, SelfLearningService_DecideRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selfLearningServiceClient) ArchiveArtefact(ctx context.Context, in *ArchiveArtefactRequest, opts ...grpc.CallOption) (*ArchiveArtefactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveArtefactResponse)
	err := c.cc.Invoke(ctx, SelfLearningService_ArchiveArtefact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selfLearningServiceClient) RestoreArtefact(ctx context.Context, in *RestoreArtefactRequest, opts ...grpc.CallOption) (*RestoreArtefactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreArtefactResponse)
	err := c.cc.Invoke(ctx, SelfLearningService_RestoreArtefact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SelfLearningServiceServer is the server API for SelfLearningService service.
// All implementations should embed UnimplementedSelfLearningServiceServer
// for forward compatibility.
//
// -----------------------------------------------------------------------------
// SelfLearningService — inspect and decide on what the agent taught itself
// -----------------------------------------------------------------------------
//
// The offline `lobslaw learned` CLI opens state.db directly, which
// means bbolt's exclusive lock, which means the node must be stopped.
// That is a fine shape for forensics and a terrible one for approval:
// approving a proposal is a routine act, and requiring a service
// outage to perform it guarantees that nobody does it — after which
// propose mode is a queue that only fills.
//
// So the same operations are reachable on a RUNNING cluster. Writes
// forward to the leader like every other write; the offline CLI stays
// for the case where the node will not start.
//
// Deliberately NOT reachable from a conversation. Approval is the act
// that decides whether the agent's own suggestion becomes something it
// follows, and routing it through the channel the agent writes in puts
// the request and the approval on the same wire. The in-channel path
// is a later, separate decision, and it will sit on the durable
// confirmation records rather than on this service.
type SelfLearningServiceServer interface {
	ListArtefacts(context.Context, *ListArtefactsRequest) (*ListArtefactsResponse, error)
	ApproveArtefact(context.Context, *ApproveArtefactRequest) (*ApproveArtefactResponse, error)
	DecideRevision(context.Context, *DecideRevisionRequest) (*DecideRevisionResponse, error)
	ArchiveArtefact(context.Context, *ArchiveArtefactRequest) (*ArchiveArtefactResponse, error)
	RestoreArtefact(context.Context, *RestoreArtefactRequest) (*RestoreArtefactResponse, error)
}

// UnimplementedSelfLearningServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSelfLearningServiceServer struct{}

func (UnimplementedSelfLearningServiceServer) ListArtefacts(context.Context, *ListArtefactsRequest) (*ListArtefactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArtefacts not implemented")
}
func (UnimplementedSelfLearningServiceServer) ApproveArtefact(context.Context, *ApproveArtefactRequest) (*ApproveArtefactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveArtefact not implemented")
}
func (UnimplementedSelfLearningServiceServer) DecideRevision(context.Context, *DecideRevisionRequest) (*DecideRevisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecideRevision not implemented")
}
func (UnimplementedSelfLearningServiceServer) ArchiveArtefact(context.Context, *ArchiveArtefactRequest) (*ArchiveArtefactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveArtefact not implemented")
}
func (UnimplementedSelfLearningServiceServer) RestoreArtefact(context.Context, *RestoreArtefactRequest) (*RestoreArtefactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreArtefact not implemented")
}
func (UnimplementedSelfLearningServiceServer) testEmbeddedByValue() {}

// UnsafeSelfLearningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SelfLearningServiceServer will
// result in compilation errors.
type UnsafeSelfLearningServiceServer interface {
	mustEmbedUnimplementedSelfLearningServiceServer()
}

func RegisterSelfLearningServiceServer(s grpc.ServiceRegistrar, srv SelfLearningServiceServer) {
	// If the following call pancis, it indicates UnimplementedSelfLearningServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SelfLearningService_ServiceDesc, srv)
}

func _SelfLearningService_ListArtefacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArtefactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfLearningServiceServer).ListArtefacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfLearningService_ListArtefacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfLearningServiceServer).ListArtefacts(ctx, req.(*ListArtefactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SelfLearningService_ApproveArtefact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveArtefactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfLearningServiceServer).ApproveArtefact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfLearningService_ApproveArtefact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfLearningServiceServer).ApproveArtefact(ctx, req.(*ApproveArtefactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SelfLearningService_DecideRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfLearningServiceServer).DecideRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfLearningService_DecideRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfLearningServiceServer).DecideRevision(ctx, req.(*DecideRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SelfLearningService_ArchiveArtefact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveArtefactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfLearningServiceServer).ArchiveArtefact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfLearningService_ArchiveArtefact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfLearningServiceServer).ArchiveArtefact(ctx, req.(*ArchiveArtefactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SelfLearningService_RestoreArtefact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreArtefactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfLearningServiceServer).RestoreArtefact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfLearningService_RestoreArtefact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfLearningServiceServer).RestoreArtefact(ctx, req.(*RestoreArtefactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SelfLearningService_ServiceDesc is the grpc.ServiceDesc for SelfLearningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SelfLearningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobslaw.v1.SelfLearningService",
	HandlerType: (*SelfLearningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListArtefacts",
			Handler:    _SelfLearningService_ListArtefacts_Handler,
		},
		{
			MethodName: "ApproveArtefact",
			Handler:    _SelfLearningService_ApproveArtefact_Handler,
		},
		{
			MethodName: "DecideRevision",
			Handler:    _SelfLearningService_DecideRevision_Handler,
		},
		{
			MethodName: "ArchiveArtefact",
			Handler:    _SelfLearningService_ArchiveArtefact_Handler,
		},
		{
			MethodName: "RestoreArtefact",
			Handler:    _SelfLearningService_RestoreArtefact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobslaw/v1/lobslaw.proto",
}

const (
	MemoryService_Store_FullMethodName        = "/lobslaw.v1.MemoryService/Store"
	MemoryService_Recall_FullMethodName       = "/lobslaw.v1.MemoryService/Recall"
	MemoryService_Search_FullMethodName       = "/lobslaw.v1.MemoryService/Search"
	MemoryService_EpisodicAdd_FullMethodName  = "/lobslaw.v1.MemoryService/EpisodicAdd"
	MemoryService_Dream_FullMethodName        = "/lobslaw.v1.MemoryService/Dream"
	MemoryService_Forget_FullMethodName       = "/lobslaw.v1.MemoryService/Forget"
	MemoryService_FindClusters_FullMethodName = "/lobslaw.v1.MemoryService/FindClusters"
)

// MemoryServiceClient is the client API for MemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemoryServiceClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	EpisodicAdd(ctx context.Context, in *EpisodicAddRequest, opts ...grpc.CallOption) (*EpisodicAddResponse, error)
	Dream(ctx context.Context, in *DreamRequest, opts ...grpc.CallOption) (*DreamResponse, error)
	Forget(ctx context.Context, in *ForgetRequest, opts ...grpc.CallOption) (*ForgetResponse, error)
	// FindClusters — deterministic near-duplicate detection for the
	// Dream-time consolidation merge flow. Pure math (pairwise cosine
	// + union-find); no LLM. See docs/MEMORY.md for the composition
	// pattern with the Adjudicator LLM interface.
	FindClusters(ctx context.Context, in *FindClustersRequest, opts ...grpc.CallOption) (*FindClustersResponse, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, MemoryService_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallResponse)
	err := c.cc.Invoke(ctx, MemoryService_Recall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MemoryService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) EpisodicAdd(ctx context.Context, in *EpisodicAddRequest, opts ...grpc.CallOption) (*EpisodicAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EpisodicAddResponse)
	err := c.cc.Invoke(ctx, MemoryService_EpisodicAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) Dream(ctx context.Context, in *DreamRequest, opts ...grpc.CallOption) (*DreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DreamResponse)
	err := c.cc.Invoke(ctx, MemoryService_Dream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) Forget(ctx context.Context, in *ForgetRequest, opts ...grpc.CallOption) (*ForgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetResponse)
	err := c.cc.Invoke(ctx, MemoryService_Forget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) FindClusters(ctx context.Context, in *FindClustersRequest, opts ...grpc.CallOption) (*FindClustersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindClustersResponse)
	err := c.cc.Invoke(ctx, MemoryService_FindClusters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServiceServer is the server API for MemoryService service.
// All implementations should embed UnimplementedMemoryServiceServer
// for forward compatibility.
type MemoryServiceServer interface {
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	Recall(context.Context, *RecallRequest) (*RecallResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	EpisodicAdd(context.Context, *EpisodicAddRequest) (*EpisodicAddResponse, error)
	Dream(context.Context, *DreamRequest) (*DreamResponse, error)
	Forget(context.Context, *ForgetRequest) (*ForgetResponse, error)
	// FindClusters — deterministic near-duplicate detection for the
	// Dream-time consolidation merge flow. Pure math (pairwise cosine
	// + union-find); no LLM. See docs/MEMORY.md for the composition
	// pattern with the Adjudicator LLM interface.
	FindClusters(context.Context, *FindClustersRequest) (*FindClustersResponse, error)
}

// UnimplementedMemoryServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryServiceServer struct{}

func (UnimplementedMemoryServiceServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedMemoryServiceServer) Recall(context.Context, *RecallRequest) (*RecallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recall not implemented")
}
func (UnimplementedMemoryServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMemoryServiceServer) EpisodicAdd(context.Context, *EpisodicAddRequest) (*EpisodicAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpisodicAdd not implemented")
}
func (UnimplementedMemoryServiceServer) Dream(context.Context, *DreamRequest) (*DreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dream not implemented")
}
func (UnimplementedMemoryServiceServer) Forget(context.Context, *ForgetRequest) (*ForgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Forget not implemented")
}
func (UnimplementedMemoryServiceServer) FindClusters(context.Context, *FindClustersRequest) (*FindClustersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindClusters not implemented")
}
func (UnimplementedMemoryServiceServer) testEmbeddedByValue() {}

// UnsafeMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServiceServer will
// result in compilation errors.
type UnsafeMemoryServiceServer interface {
	mustEmbedUnimplementedMemoryServiceServer()
}

func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedMemoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_Recall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Recall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Recall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Recall(ctx, req.(*RecallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_EpisodicAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpisodicAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).EpisodicAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_EpisodicAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).EpisodicAdd(ctx, req.(*EpisodicAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_Dream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Dream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Dream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Dream(ctx, req.(*DreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_Forget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Forget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Forget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Forget(ctx, req.(*ForgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_FindClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).FindClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_FindClusters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).FindClusters(ctx, req.(*FindClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobslaw.v1.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _MemoryService_Store_Handler,
		},
		{
			MethodName: "Recall",
			Handler:    _MemoryService_Recall_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _MemoryService_Search_Handler,
		},
		{
			MethodName: "EpisodicAdd",
			Handler:    _MemoryService_EpisodicAdd_Handler,
		},
		{
			MethodName: "Dream",
			Handler:    _MemoryService_Dream_Handler,
		},
		{
			MethodName: "Forget",
			Handler:    _MemoryService_Forget_Handler,
		},
		{
			MethodName: "FindClusters",
			Handler:    _MemoryService_FindClusters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobslaw/v1/lobslaw.proto",
}

const (
	PolicyService_Evaluate_FullMethodName            = "/lobslaw.v1.PolicyService/Evaluate"
	PolicyService_SyncRules_FullMethodName           = "/lobslaw.v1.PolicyService/SyncRules"
	PolicyService_AddRule_FullMethodName             = "/lobslaw.v1.PolicyService/AddRule"
	PolicyService_RevokeApprovalRules_FullMethodName = "/lobslaw.v1.PolicyService/RevokeApprovalRules"
	PolicyService_RequestConfirmation_FullMethodName = "/lobslaw.v1.PolicyService/RequestConfirmation"
)

// PolicyServiceClient is the client API for PolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyServiceClient interface {
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	SyncRules(ctx context.Context, in *SyncRulesRequest, opts ...grpc.CallOption) (*SyncRulesResponse, error)
	AddRule(ctx context.Context, in *AddRuleRequest, opts ...grpc.CallOption) (*AddRuleResponse, error)
	// RevokeApprovalRules deletes rules minted by an "always" approval.
	//
	// Scoped to that class in its NAME rather than by a prefix the
	// caller supplies. The guarantee an operator relies on — that
	// revoking their approvals cannot touch a rule they wrote by hand —
	// is enforced on the server, because a check in the client is one an
	// attacker replaces.
	//
	// There is deliberately no unscoped delete. Nothing needs one, and
	// an RPC that can remove any policy rule is the one you would most
	// like not to have shipped.
	RevokeApprovalRules(ctx context.Context, in *RevokeApprovalRulesRequest, opts ...grpc.CallOption) (*RevokeApprovalRulesResponse, error)
	RequestConfirmation(ctx context.Context, in *RequestConfirmationRequest, opts ...grpc.CallOption) (*RequestConfirmationResponse, error)
}

type policyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyServiceClient(cc grpc.ClientConnInterface) PolicyServiceClient {
	return &policyServiceClient{cc}
}

func (c *policyServiceClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, PolicyService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) SyncRules(ctx context.Context, in *SyncRulesRequest, opts ...grpc.CallOption) (*SyncRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncRulesResponse)
	err := c.cc.Invoke(ctx, PolicyService_SyncRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) AddRule(ctx context.Context, in *AddRuleRequest, opts ...grpc.CallOption) (*AddRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRuleResponse)
	err := c.cc.Invoke(ctx, PolicyService_AddRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) RevokeApprovalRules(ctx context.Context, in *RevokeApprovalRulesRequest, opts ...grpc.CallOption) (*RevokeApprovalRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeApprovalRulesResponse)
	err := c.cc.Invoke(ctx, PolicyService_RevokeApprovalRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) RequestConfirmation(ctx context.Context, in *RequestConfirmationRequest, opts ...grpc.CallOption) (*RequestConfirmationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestConfirmationResponse)
	err := c.cc.Invoke(ctx, PolicyService_RequestConfirmation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServiceServer is the server API for PolicyService service.
// All implementations should embed UnimplementedPolicyServiceServer
// for forward compatibility.
type PolicyServiceServer interface {
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	SyncRules(context.Context, *SyncRulesRequest) (*SyncRulesResponse, error)
	AddRule(context.Context, *AddRuleRequest) (*AddRuleResponse, error)
	// RevokeApprovalRules deletes rules minted by an "always" approval.
	//
	// Scoped to that class in its NAME rather than by a prefix the
	// caller supplies. The guarantee an operator relies on — that
	// revoking their approvals cannot touch a rule they wrote by hand —
	// is enforced on the server, because a check in the client is one an
	// attacker replaces.
	//
	// There is deliberately no unscoped delete. Nothing needs one, and
	// an RPC that can remove any policy rule is the one you would most
	// like not to have shipped.
	RevokeApprovalRules(context.Context, *RevokeApprovalRulesRequest) (*RevokeApprovalRulesResponse, error)
	RequestConfirmation(context.Context, *RequestConfirmationRequest) (*RequestConfirmationResponse, error)
}

// UnimplementedPolicyServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyServiceServer struct{}

func (UnimplementedPolicyServiceServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedPolicyServiceServer) SyncRules(context.Context, *SyncRulesRequest) (*SyncRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncRules not implemented")
}
func (UnimplementedPolicyServiceServer) AddRule(context.Context, *AddRuleRequest) (*AddRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRule not implemented")
}
func (UnimplementedPolicyServiceServer) RevokeApprovalRules(context.Context, *RevokeApprovalRulesRequest) (*RevokeApprovalRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeApprovalRules not implemented")
}
func (UnimplementedPolicyServiceServer) RequestConfirmation(context.Context, *RequestConfirmationRequest) (*RequestConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestConfirmation not implemented")
}
func (UnimplementedPolicyServiceServer) testEmbeddedByValue() {}

// UnsafePolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServiceServer will
// result in compilation errors.
type UnsafePolicyServiceServer interface {
	mustEmbedUnimplementedPolicyServiceServer()
}

func RegisterPolicyServiceServer(s grpc.ServiceRegistrar, srv PolicyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyService_ServiceDesc, srv)
}

func _PolicyService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_SyncRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).SyncRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_SyncRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).SyncRules(ctx, req.(*SyncRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_AddRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).AddRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_AddRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).AddRule(ctx, req.(*AddRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_RevokeApprovalRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeApprovalRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).RevokeApprovalRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_RevokeApprovalRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).RevokeApprovalRules(ctx, req.(*RevokeApprovalRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_RequestConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).RequestConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_RequestConfirmation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).RequestConfirmation(ctx, req.(*RequestConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyService_ServiceDesc is the grpc.ServiceDesc for PolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobslaw.v1.PolicyService",
	HandlerType: (*PolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _PolicyService_Evaluate_Handler,
		},
		{
			MethodName: "SyncRules",
			Handler:    _PolicyService_SyncRules_Handler,
		},
		{
			MethodName: "AddRule",
			Handler:    _PolicyService_AddRule_Handler,
		},
		{
			MethodName: "RevokeApprovalRules",
			Handler:    _PolicyService_RevokeApprovalRules_Handler,
		},
		{
			MethodName: "RequestConfirmation",
			Handler:    _PolicyService_RequestConfirmation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobslaw/v1/lobslaw.proto",
}

const (
	AgentService_InvokeTool_FullMethodName     = "/lobslaw.v1.AgentService/InvokeTool"
	AgentService_ListTools_FullMethodName      = "/lobslaw.v1.AgentService/ListTools"
	AgentService_ProcessMessage_FullMethodName = "/lobslaw.v1.AgentService/ProcessMessage"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	InvokeTool(ctx context.Context, in *InvokeToolRequest, opts ...grpc.CallOption) (*InvokeToolResponse, error)
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	ProcessMessage(ctx context.Context, in *ProcessMessageRequest, opts ...grpc.CallOption) (*ProcessMessageResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) InvokeTool(ctx context.Context, in *InvokeToolRequest, opts ...grpc.CallOption) (*InvokeToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeToolResponse)
	err := c.cc.Invoke(ctx, AgentService_InvokeTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ProcessMessage(ctx context.Context, in *ProcessMessageRequest, opts ...grpc.CallOption) (*ProcessMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessMessageResponse)
	err := c.cc.Invoke(ctx, AgentService_ProcessMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations should embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	InvokeTool(context.Context, *InvokeToolRequest) (*InvokeToolResponse, error)
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	ProcessMessage(context.Context, *ProcessMessageRequest) (*ProcessMessageResponse, error)
}

// UnimplementedAgentServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) InvokeTool(context.Context, *InvokeToolRequest) (*InvokeToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeTool not implemented")
}
func (UnimplementedAgentServiceServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedAgentServiceServer) ProcessMessage(context.Context, *ProcessMessageRequest) (*ProcessMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMessage not implemented")
}
func (UnimplementedAgentServiceServer) testEmbeddedByValue() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_InvokeTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InvokeTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InvokeTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InvokeTool(ctx, req.(*InvokeToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ProcessMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ProcessMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ProcessMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ProcessMessage(ctx, req.(*ProcessMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobslaw.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeTool",
			Handler:    _AgentService_InvokeTool_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _AgentService_ListTools_Handler,
		},
		{
			MethodName: "ProcessMessage",
			Handler:    _AgentService_ProcessMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobslaw/v1/lobslaw.proto",
}

const (
	ChannelService_HandleUpdate_FullMethodName = "/lobslaw.v1.ChannelService/HandleUpdate"
	ChannelService_Prompt_FullMethodName       = "/lobslaw.v1.ChannelService/Prompt"
)

// ChannelServiceClient is the client API for ChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelServiceClient interface {
	HandleUpdate(ctx context.Context, in *HandleUpdateRequest, opts ...grpc.CallOption) (*HandleUpdateResponse, error)
	Prompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*PromptResponse, error)
}

type channelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelServiceClient(cc grpc.ClientConnInterface) ChannelServiceClient {
	return &channelServiceClient{cc}
}

func (c *channelServiceClient) HandleUpdate(ctx context.Context, in *HandleUpdateRequest, opts ...grpc.CallOption) (*HandleUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleUpdateResponse)
	err := c.cc.Invoke(ctx, ChannelService_HandleUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) Prompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*PromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptResponse)
	err := c.cc.Invoke(ctx, ChannelService_Prompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelServiceServer is the server API for ChannelService service.
// All implementations should embed UnimplementedChannelServiceServer
// for forward compatibility.
type ChannelServiceServer interface {
	HandleUpdate(context.Context, *HandleUpdateRequest) (*HandleUpdateResponse, error)
	Prompt(context.Context, *PromptRequest) (*PromptResponse, error)
}

// UnimplementedChannelServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelServiceServer struct{}

func (UnimplementedChannelServiceServer) HandleUpdate(context.Context, *HandleUpdateRequest) (*HandleUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleUpdate not implemented")
}
func (UnimplementedChannelServiceServer) Prompt(context.Context, *PromptRequest) (*PromptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prompt not implemented")
}
func (UnimplementedChannelServiceServer) testEmbeddedByValue() {}

// UnsafeChannelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelServiceServer will
// result in compilation errors.
type UnsafeChannelServiceServer interface {
	mustEmbedUnimplementedChannelServiceServer()
}

func RegisterChannelServiceServer(s grpc.ServiceRegistrar, srv ChannelServiceServer) {
	// If the following call pancis, it indicates UnimplementedChannelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelService_ServiceDesc, srv)
}

func _ChannelService_HandleUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).HandleUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_HandleUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).HandleUpdate(ctx, req.(*HandleUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_Prompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).Prompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_Prompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).Prompt(ctx, req.(*PromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelService_ServiceDesc is the grpc.ServiceDesc for ChannelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobslaw.v1.ChannelService",
	HandlerType: (*ChannelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleUpdate",
			Handler:    _ChannelService_HandleUpdate_Handler,
		},
		{
			MethodName: "Prompt",
			Handler:    _ChannelService_Prompt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobslaw/v1/lobslaw.proto",
}

const (
	PlanService_GetPlan_FullMethodName          = "/lobslaw.v1.PlanService/GetPlan"
	PlanService_AddCommitment_FullMethodName    = "/lobslaw.v1.PlanService/AddCommitment"
	PlanService_CancelCommitment_FullMethodName = "/lobslaw.v1.PlanService/CancelCommitment"
)

// PlanServiceClient is the client API for PlanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlanServiceClient interface {
	GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*GetPlanResponse, error)
	AddCommitment(ctx context.Context, in *AddCommitmentRequest, opts ...grpc.CallOption) (*AddCommitmentResponse, error)
	CancelCommitment(ctx context.Context, in *CancelCommitmentRequest, opts ...grpc.CallOption) (*CancelCommitmentResponse, error)
}

type planServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlanServiceClient(cc grpc.ClientConnInterface) PlanServiceClient {
	return &planServiceClient{cc}
}

func (c *planServiceClient) GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*GetPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanResponse)
	err := c.cc.Invoke(ctx, PlanService_GetPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) AddCommitment(ctx context.Context, in *AddCommitmentRequest, opts ...grpc.CallOption) (*AddCommitmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCommitmentResponse)
	err := c.cc.Invoke(ctx, PlanService_AddCommitment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) CancelCommitment(ctx context.Context, in *CancelCommitmentRequest, opts ...grpc.CallOption) (*CancelCommitmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelCommitmentResponse)
	err := c.cc.Invoke(ctx, PlanService_CancelCommitment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlanServiceServer is the server API for PlanService service.
// All implementations should embed UnimplementedPlanServiceServer
// for forward compatibility.
type PlanServiceServer interface {
	GetPlan(context.Context, *GetPlanRequest) (*GetPlanResponse, error)
	AddCommitment(context.Context, *AddCommitmentRequest) (*AddCommitmentResponse, error)
	CancelCommitment(context.Context, *CancelCommitmentRequest) (*CancelCommitmentResponse, error)
}

// UnimplementedPlanServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlanServiceServer struct{}

func (UnimplementedPlanServiceServer) GetPlan(context.Context, *GetPlanRequest) (*GetPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlan not implemented")
}
func (UnimplementedPlanServiceServer) AddCommitment(context.Context, *AddCommitmentRequest) (*AddCommitmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCommitment not implemented")
}
func (UnimplementedPlanServiceServer) CancelCommitment(context.Context, *CancelCommitmentRequest) (*CancelCommitmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCommitment not implemented")
}
func (UnimplementedPlanServiceServer) testEmbeddedByValue() {}

// UnsafePlanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlanServiceServer will
// result in compilation errors.
type UnsafePlanServiceServer interface {
	mustEmbedUnimplementedPlanServiceServer()
}

func RegisterPlanServiceServer(s grpc.ServiceRegistrar, srv PlanServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlanService_ServiceDesc, srv)
}

func _PlanService_GetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_GetPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).GetPlan(ctx, req.(*GetPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_AddCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommitmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).AddCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_AddCommitment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).AddCommitment(ctx, req.(*AddCommitmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_CancelCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCommitmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).CancelCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_CancelCommitment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).CancelCommitment(ctx, req.(*CancelCommitmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlanService_ServiceDesc is the grpc.ServiceDesc for PlanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobslaw.v1.PlanService",
	HandlerType: (*PlanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlan",
			Handler:    _PlanService_GetPlan_Handler,
		},
		{
			MethodName: "AddCommitment",
			Handler:    _PlanService_AddCommitment_Handler,
		},
		{
			MethodName: "CancelCommitment",
			Handler:    _PlanService_CancelCommitment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobslaw/v1/lobslaw.proto",
}

const (
	AuditService_Append_FullMethodName      = "/lobslaw.v1.AuditService/Append"
	AuditService_Query_FullMethodName       = "/lobslaw.v1.AuditService/Query"
	AuditService_VerifyChain_FullMethodName = "/lobslaw.v1.AuditService/VerifyChain"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditServiceClient interface {
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	VerifyChain(ctx context.Context, in *VerifyChainRequest, opts ...grpc.CallOption) (*VerifyChainResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, AuditService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, AuditService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) VerifyChain(ctx context.Context, in *VerifyChainRequest, opts ...grpc.CallOption) (*VerifyChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyChainResponse)
	err := c.cc.Invoke(ctx, AuditService_VerifyChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations should embed UnimplementedAuditServiceServer
// for forward compatibility.
type AuditServiceServer interface {
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	VerifyChain(context.Context, *VerifyChainRequest) (*VerifyChainResponse, error)
}

// UnimplementedAuditServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedAuditServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedAuditServiceServer) VerifyChain(context.Context, *VerifyChainRequest) (*VerifyChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyChain not implemented")
}
func (UnimplementedAuditServiceServer) testEmbeddedByValue() {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_VerifyChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).VerifyChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_VerifyChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).VerifyChain(ctx, req.(*VerifyChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobslaw.v1.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _AuditService_Append_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _AuditService_Query_Handler,
		},
		{
			MethodName: "VerifyChain",
			Handler:    _AuditService_VerifyChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobslaw/v1/lobslaw.proto",
}

const (
	StorageService_AddMount_FullMethodName    = "/lobslaw.v1.StorageService/AddMount"
	StorageService_RemoveMount_FullMethodName = "/lobslaw.v1.StorageService/RemoveMount"
	StorageService_ListMounts_FullMethodName  = "/lobslaw.v1.StorageService/ListMounts"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServiceClient interface {
	AddMount(ctx context.Context, in *AddMountRequest, opts ...grpc.CallOption) (*AddMountResponse, error)
	RemoveMount(ctx context.Context, in *RemoveMountRequest, opts ...grpc.CallOption) (*RemoveMountResponse, error)
	ListMounts(ctx context.Context, in *ListMountsRequest, opts ...grpc.CallOption) (*ListMountsResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) AddMount(ctx context.Context, in *AddMountRequest, opts ...grpc.CallOption) (*AddMountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMountResponse)
	err := c.cc.Invoke(ctx, StorageService_AddMount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) RemoveMount(ctx context.Context, in *RemoveMountRequest, opts ...grpc.CallOption) (*RemoveMountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMountResponse)
	err := c.cc.Invoke(ctx, StorageService_RemoveMount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListMounts(ctx context.Context, in *ListMountsRequest, opts ...grpc.CallOption) (*ListMountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMountsResponse)
	err := c.cc.Invoke(ctx, StorageService_ListMounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations should embed UnimplementedStorageServiceServer
// for forward compatibility.
type StorageServiceServer interface {
	AddMount(context.Context, *AddMountRequest) (*AddMountResponse, error)
	RemoveMount(context.Context, *RemoveMountRequest) (*RemoveMountResponse, error)
	ListMounts(context.Context, *ListMountsRequest) (*ListMountsResponse, error)
}

// UnimplementedStorageServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) AddMount(context.Context, *AddMountRequest) (*AddMountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMount not implemented")
}
func (UnimplementedStorageServiceServer) RemoveMount(context.Context, *RemoveMountRequest) (*RemoveMountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMount not implemented")
}
func (UnimplementedStorageServiceServer) ListMounts(context.Context, *ListMountsRequest) (*ListMountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMounts not implemented")
}
func (UnimplementedStorageServiceServer) testEmbeddedByValue() {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_AddMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).AddMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_AddMount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).AddMount(ctx, req.(*AddMountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_RemoveMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).RemoveMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_RemoveMount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).RemoveMount(ctx, req.(*RemoveMountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListMounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListMounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ListMounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListMounts(ctx, req.(*ListMountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobslaw.v1.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMount",
			Handler:    _StorageService_AddMount_Handler,
		},
		{
			MethodName: "RemoveMount",
			Handler:    _StorageService_RemoveMount_Handler,
		},
		{
			MethodName: "ListMounts",
			Handler:    _StorageService_ListMounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobslaw/v1/lobslaw.proto",
}
