// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rafttransport/v1/rafttransport.proto

package rafttransportv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCHeader struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion int32                  `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Id              []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Addr            []byte                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RPCHeader) Reset() {
	*x = RPCHeader{}
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCHeader) ProtoMessage() {}

func (x *RPCHeader) ProtoReflect() protoreflect.Message {
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCHeader.ProtoReflect.Descriptor instead.
func (*RPCHeader) Descriptor() ([]byte, []int) {
	return file_rafttransport_v1_rafttransport_proto_rawDescGZIP(), []int{0}
}

func (x *RPCHeader) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RPCHeader) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RPCHeader) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Extensions    []byte                 `protobuf:"bytes,5,opt,name=extensions,proto3" json:"extensions,omitempty"`
	AppendedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=appended_at,json=appendedAt,proto3" json:"appended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_rafttransport_v1_rafttransport_proto_rawDescGZIP(), []int{1}
}

func (x *Log) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Log) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Log) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Log) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Log) GetExtensions() []byte {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Log) GetAppendedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AppendedAt
	}
	return nil
}

type AppendEntriesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Header            *RPCHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Term              uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Leader            []byte                 `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	PrevLogEntry      uint64                 `protobuf:"varint,4,opt,name=prev_log_entry,json=prevLogEntry,proto3" json:"prev_log_entry,omitempty"`
	PrevLogTerm       uint64                 `protobuf:"varint,5,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries           []*Log                 `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommitIndex uint64                 `protobuf:"varint,7,opt,name=leader_commit_index,json=leaderCommitIndex,proto3" json:"leader_commit_index,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_rafttransport_v1_rafttransport_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEntriesRequest) GetHeader() *RPCHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AppendEntriesRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeader() []byte {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *AppendEntriesRequest) GetPrevLogEntry() uint64 {
	if x != nil {
		return x.PrevLogEntry
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*Log {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommitIndex() uint64 {
	if x != nil {
		return x.LeaderCommitIndex
	}
	return 0
}

type AppendEntriesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Header         *RPCHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Term           uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LastLog        uint64                 `protobuf:"varint,3,opt,name=last_log,json=lastLog,proto3" json:"last_log,omitempty"`
	Success        bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	NoRetryBackoff bool                   `protobuf:"varint,5,opt,name=no_retry_backoff,json=noRetryBackoff,proto3" json:"no_retry_backoff,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_rafttransport_v1_rafttransport_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEntriesResponse) GetHeader() *RPCHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AppendEntriesResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetLastLog() uint64 {
	if x != nil {
		return x.LastLog
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesResponse) GetNoRetryBackoff() bool {
	if x != nil {
		return x.NoRetryBackoff
	}
	return false
}

type RequestVoteRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Header             *RPCHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Term               uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Candidate          []byte                 `protobuf:"bytes,3,opt,name=candidate,proto3" json:"candidate,omitempty"`
	LastLogIndex       uint64                 `protobuf:"varint,4,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm        uint64                 `protobuf:"varint,5,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	LeadershipTransfer bool                   `protobuf:"varint,6,opt,name=leadership_transfer,json=leadershipTransfer,proto3" json:"leadership_transfer,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_rafttransport_v1_rafttransport_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteRequest) GetHeader() *RPCHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RequestVoteRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidate() []byte {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *RequestVoteRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *RequestVoteRequest) GetLeadershipTransfer() bool {
	if x != nil {
		return x.LeadershipTransfer
	}
	return false
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RPCHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Peers         []byte                 `protobuf:"bytes,3,opt,name=peers,proto3" json:"peers,omitempty"`
	Granted       bool                   `protobuf:"varint,4,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_rafttransport_v1_rafttransport_proto_rawDescGZIP(), []int{5}
}

func (x *RequestVoteResponse) GetHeader() *RPCHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RequestVoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetPeers() []byte {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RequestVoteResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

type InstallSnapshotHeader struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Header             *RPCHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SnapshotVersion    int32                  `protobuf:"varint,2,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Term               uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Leader             []byte                 `protobuf:"bytes,4,opt,name=leader,proto3" json:"leader,omitempty"`
	LastLogIndex       uint64                 `protobuf:"varint,5,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm        uint64                 `protobuf:"varint,6,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	Peers              []byte                 `protobuf:"bytes,7,opt,name=peers,proto3" json:"peers,omitempty"`
	Configuration      []byte                 `protobuf:"bytes,8,opt,name=configuration,proto3" json:"configuration,omitempty"`
	ConfigurationIndex uint64                 `protobuf:"varint,9,opt,name=configuration_index,json=configurationIndex,proto3" json:"configuration_index,omitempty"`
	Size               int64                  `protobuf:"varint,10,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InstallSnapshotHeader) Reset() {
	*x = InstallSnapshotHeader{}
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotHeader) ProtoMessage() {}

func (x *InstallSnapshotHeader) ProtoReflect() protoreflect.Message {
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotHeader.ProtoReflect.Descriptor instead.
func (*InstallSnapshotHeader) Descriptor() ([]byte, []int) {
	return file_rafttransport_v1_rafttransport_proto_rawDescGZIP(), []int{6}
}

func (x *InstallSnapshotHeader) GetHeader() *RPCHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InstallSnapshotHeader) GetSnapshotVersion() int32 {
	if x != nil {
		return x.SnapshotVersion
	}
	return 0
}

func (x *InstallSnapshotHeader) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotHeader) GetLeader() []byte {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *InstallSnapshotHeader) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *InstallSnapshotHeader) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *InstallSnapshotHeader) GetPeers() []byte {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *InstallSnapshotHeader) GetConfiguration() []byte {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *InstallSnapshotHeader) GetConfigurationIndex() uint64 {
	if x != nil {
		return x.ConfigurationIndex
	}
	return 0
}

func (x *InstallSnapshotHeader) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// InstallSnapshotRequest is streamed: the first message in the stream
// carries the header, subsequent messages carry snapshot bytes.
type InstallSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*InstallSnapshotRequest_Header
	//	*InstallSnapshotRequest_Data
	Content       isInstallSnapshotRequest_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotRequest) Reset() {
	*x = InstallSnapshotRequest{}
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotRequest) ProtoMessage() {}

func (x *InstallSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotRequest.ProtoReflect.Descriptor instead.
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_rafttransport_v1_rafttransport_proto_rawDescGZIP(), []int{7}
}

func (x *InstallSnapshotRequest) GetContent() isInstallSnapshotRequest_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *InstallSnapshotRequest) GetHeader() *InstallSnapshotHeader {
	if x != nil {
		if x, ok := x.Content.(*InstallSnapshotRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *InstallSnapshotRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Content.(*InstallSnapshotRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isInstallSnapshotRequest_Content interface {
	isInstallSnapshotRequest_Content()
}

type InstallSnapshotRequest_Header struct {
	Header *InstallSnapshotHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type InstallSnapshotRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*InstallSnapshotRequest_Header) isInstallSnapshotRequest_Content() {}

func (*InstallSnapshotRequest_Data) isInstallSnapshotRequest_Content() {}

type InstallSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RPCHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotResponse) Reset() {
	*x = InstallSnapshotResponse{}
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotResponse) ProtoMessage() {}

func (x *InstallSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotResponse.ProtoReflect.Descriptor instead.
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_rafttransport_v1_rafttransport_proto_rawDescGZIP(), []int{8}
}

func (x *InstallSnapshotResponse) GetHeader() *RPCHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InstallSnapshotResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TimeoutNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RPCHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutNowRequest) Reset() {
	*x = TimeoutNowRequest{}
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutNowRequest) ProtoMessage() {}

func (x *TimeoutNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutNowRequest.ProtoReflect.Descriptor instead.
func (*TimeoutNowRequest) Descriptor() ([]byte, []int) {
	return file_rafttransport_v1_rafttransport_proto_rawDescGZIP(), []int{9}
}

func (x *TimeoutNowRequest) GetHeader() *RPCHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type TimeoutNowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RPCHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutNowResponse) Reset() {
	*x = TimeoutNowResponse{}
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutNowResponse) ProtoMessage() {}

func (x *TimeoutNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rafttransport_v1_rafttransport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutNowResponse.ProtoReflect.Descriptor instead.
func (*TimeoutNowResponse) Descriptor() ([]byte, []int) {
	return file_rafttransport_v1_rafttransport_proto_rawDescGZIP(), []int{10}
}

func (x *TimeoutNowResponse) GetHeader() *RPCHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TimeoutNowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rafttransport_v1_rafttransport_proto protoreflect.FileDescriptor

const file_rafttransport_v1_rafttransport_proto_rawDesc = "" +
	"\n" +
	"$rafttransport/v1/rafttransport.proto\x12\x10rafttransport.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Z\n" +
	"\tRPCHeader\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\x05R\x0fprotocolVersion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\fR\x04addr\"\xb4\x01\n" +
	"\x03Log\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"extensions\x18\x05 \x01(\fR\n" +
	"extensions\x12;\n" +
	"\vappended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"appendedAt\"\xa2\x02\n" +
	"\x14AppendEntriesRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.rafttransport.v1.RPCHeaderR\x06header\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\fR\x06leader\x12$\n" +
	"\x0eprev_log_entry\x18\x04 \x01(\x04R\fprevLogEntry\x12\"\n" +
	"\rprev_log_term\x18\x05 \x01(\x04R\vprevLogTerm\x12/\n" +
	"\aentries\x18\x06 \x03(\v2\x15.rafttransport.v1.LogR\aentries\x12.\n" +
	"\x13leader_commit_index\x18\a \x01(\x04R\x11leaderCommitIndex\"\xbf\x01\n" +
	"\x15AppendEntriesResponse\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.rafttransport.v1.RPCHeaderR\x06header\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x19\n" +
	"\blast_log\x18\x03 \x01(\x04R\alastLog\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12(\n" +
	"\x10no_retry_backoff\x18\x05 \x01(\bR\x0enoRetryBackoff\"\xf6\x01\n" +
	"\x12RequestVoteRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.rafttransport.v1.RPCHeaderR\x06header\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x1c\n" +
	"\tcandidate\x18\x03 \x01(\fR\tcandidate\x12$\n" +
	"\x0elast_log_index\x18\x04 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x05 \x01(\x04R\vlastLogTerm\x12/\n" +
	"\x13leadership_transfer\x18\x06 \x01(\bR\x12leadershipTransfer\"\x8e\x01\n" +
	"\x13RequestVoteResponse\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.rafttransport.v1.RPCHeaderR\x06header\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x14\n" +
	"\x05peers\x18\x03 \x01(\fR\x05peers\x12\x18\n" +
	"\agranted\x18\x04 \x01(\bR\agranted\"\xee\x02\n" +
	"\x15InstallSnapshotHeader\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.rafttransport.v1.RPCHeaderR\x06header\x12)\n" +
	"\x10snapshot_version\x18\x02 \x01(\x05R\x0fsnapshotVersion\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x16\n" +
	"\x06leader\x18\x04 \x01(\fR\x06leader\x12$\n" +
	"\x0elast_log_index\x18\x05 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x06 \x01(\x04R\vlastLogTerm\x12\x14\n" +
	"\x05peers\x18\a \x01(\fR\x05peers\x12$\n" +
	"\rconfiguration\x18\b \x01(\fR\rconfiguration\x12/\n" +
	"\x13configuration_index\x18\t \x01(\x04R\x12configurationIndex\x12\x12\n" +
	"\x04size\x18\n" +
	" \x01(\x03R\x04size\"|\n" +
	"\x16InstallSnapshotRequest\x12A\n" +
	"\x06header\x18\x01 \x01(\v2'.rafttransport.v1.InstallSnapshotHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\acontent\"|\n" +
	"\x17InstallSnapshotResponse\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.rafttransport.v1.RPCHeaderR\x06header\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"H\n" +
	"\x11TimeoutNowRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.rafttransport.v1.RPCHeaderR\x06header\"c\n" +
	"\x12TimeoutNowResponse\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.rafttransport.v1.RPCHeaderR\x06header\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\x85\x04\n" +
	"\x14RaftTransportService\x12`\n" +
	"\rAppendEntries\x12&.rafttransport.v1.AppendEntriesRequest\x1a'.rafttransport.v1.AppendEntriesResponse\x12Z\n" +
	"\vRequestVote\x12$.rafttransport.v1.RequestVoteRequest\x1a%.rafttransport.v1.RequestVoteResponse\x12h\n" +
	"\x0fInstallSnapshot\x12(.rafttransport.v1.InstallSnapshotRequest\x1a).rafttransport.v1.InstallSnapshotResponse(\x01\x12W\n" +
	"\n" +
	"TimeoutNow\x12#.rafttransport.v1.TimeoutNowRequest\x1a$.rafttransport.v1.TimeoutNowResponse\x12l\n" +
	"\x15AppendEntriesPipeline\x12&.rafttransport.v1.AppendEntriesRequest\x1a'.rafttransport.v1.AppendEntriesResponse(\x010\x01B\xd6\x01\n" +
	"\x14com.rafttransport.v1B\x12RafttransportProtoP\x01ZIgithub.com/jmylchreest/lobslaw/pkg/proto/rafttransport/v1;rafttransportv1\xa2\x02\x03RXX\xaa\x02\x10Rafttransport.V1\xca\x02\x10Rafttransport\\V1\xe2\x02\x1cRafttransport\\V1\\GPBMetadata\xea\x02\x11Rafttransport::V1b\x06proto3"

var (
	file_rafttransport_v1_rafttransport_proto_rawDescOnce sync.Once
	file_rafttransport_v1_rafttransport_proto_rawDescData []byte
)

func file_rafttransport_v1_rafttransport_proto_rawDescGZIP() []byte {
	file_rafttransport_v1_rafttransport_proto_rawDescOnce.Do(func() {
		file_rafttransport_v1_rafttransport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rafttransport_v1_rafttransport_proto_rawDesc), len(file_rafttransport_v1_rafttransport_proto_rawDesc)))
	})
	return file_rafttransport_v1_rafttransport_proto_rawDescData
}

var file_rafttransport_v1_rafttransport_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rafttransport_v1_rafttransport_proto_goTypes = []any{
	(*RPCHeader)(nil),               // 0: rafttransport.v1.RPCHeader
	(*Log)(nil),                     // 1: rafttransport.v1.Log
	(*AppendEntriesRequest)(nil),    // 2: rafttransport.v1.AppendEntriesRequest
	(*AppendEntriesResponse)(nil),   // 3: rafttransport.v1.AppendEntriesResponse
	(*RequestVoteRequest)(nil),      // 4: rafttransport.v1.RequestVoteRequest
	(*RequestVoteResponse)(nil),     // 5: rafttransport.v1.RequestVoteResponse
	(*InstallSnapshotHeader)(nil),   // 6: rafttransport.v1.InstallSnapshotHeader
	(*InstallSnapshotRequest)(nil),  // 7: rafttransport.v1.InstallSnapshotRequest
	(*InstallSnapshotResponse)(nil), // 8: rafttransport.v1.InstallSnapshotResponse
	(*TimeoutNowRequest)(nil),       // 9: rafttransport.v1.TimeoutNowRequest
	(*TimeoutNowResponse)(nil),      // 10: rafttransport.v1.TimeoutNowResponse
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_rafttransport_v1_rafttransport_proto_depIdxs = []int32{
	11, // 0: rafttransport.v1.Log.appended_at:type_name -> google.protobuf.Timestamp
	0,  // 1: rafttransport.v1.AppendEntriesRequest.header:type_name -> rafttransport.v1.RPCHeader
	1,  // 2: rafttransport.v1.AppendEntriesRequest.entries:type_name -> rafttransport.v1.Log
	0,  // 3: rafttransport.v1.AppendEntriesResponse.header:type_name -> rafttransport.v1.RPCHeader
	0,  // 4: rafttransport.v1.RequestVoteRequest.header:type_name -> rafttransport.v1.RPCHeader
	0,  // 5: rafttransport.v1.RequestVoteResponse.header:type_name -> rafttransport.v1.RPCHeader
	0,  // 6: rafttransport.v1.InstallSnapshotHeader.header:type_name -> rafttransport.v1.RPCHeader
	6,  // 7: rafttransport.v1.InstallSnapshotRequest.header:type_name -> rafttransport.v1.InstallSnapshotHeader
	0,  // 8: rafttransport.v1.InstallSnapshotResponse.header:type_name -> rafttransport.v1.RPCHeader
	0,  // 9: rafttransport.v1.TimeoutNowRequest.header:type_name -> rafttransport.v1.RPCHeader
	0,  // 10: rafttransport.v1.TimeoutNowResponse.header:type_name -> rafttransport.v1.RPCHeader
	2,  // 11: rafttransport.v1.RaftTransportService.AppendEntries:input_type -> rafttransport.v1.AppendEntriesRequest
	4,  // 12: rafttransport.v1.RaftTransportService.RequestVote:input_type -> rafttransport.v1.RequestVoteRequest
	7,  // 13: rafttransport.v1.RaftTransportService.InstallSnapshot:input_type -> rafttransport.v1.InstallSnapshotRequest
	9,  // 14: rafttransport.v1.RaftTransportService.TimeoutNow:input_type -> rafttransport.v1.TimeoutNowRequest
	2,  // 15: rafttransport.v1.RaftTransportService.AppendEntriesPipeline:input_type -> rafttransport.v1.AppendEntriesRequest
	3,  // 16: rafttransport.v1.RaftTransportService.AppendEntries:output_type -> rafttransport.v1.AppendEntriesResponse
	5,  // 17: rafttransport.v1.RaftTransportService.RequestVote:output_type -> rafttransport.v1.RequestVoteResponse
	8,  // 18: rafttransport.v1.RaftTransportService.InstallSnapshot:output_type -> rafttransport.v1.InstallSnapshotResponse
	10, // 19: rafttransport.v1.RaftTransportService.TimeoutNow:output_type -> rafttransport.v1.TimeoutNowResponse
	3,  // 20: rafttransport.v1.RaftTransportService.AppendEntriesPipeline:output_type -> rafttransport.v1.AppendEntriesResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_rafttransport_v1_rafttransport_proto_init() }
func file_rafttransport_v1_rafttransport_proto_init() {
	if File_rafttransport_v1_rafttransport_proto != nil {
		return
	}
	file_rafttransport_v1_rafttransport_proto_msgTypes[7].OneofWrappers = []any{
		(*InstallSnapshotRequest_Header)(nil),
		(*InstallSnapshotRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rafttransport_v1_rafttransport_proto_rawDesc), len(file_rafttransport_v1_rafttransport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rafttransport_v1_rafttransport_proto_goTypes,
		DependencyIndexes: file_rafttransport_v1_rafttransport_proto_depIdxs,
		MessageInfos:      file_rafttransport_v1_rafttransport_proto_msgTypes,
	}.Build()
	File_rafttransport_v1_rafttransport_proto = out.File
	file_rafttransport_v1_rafttransport_proto_goTypes = nil
	file_rafttransport_v1_rafttransport_proto_depIdxs = nil
}
