package skills

import (
	"os"
	"path/filepath"
	"testing"
)

// Every skill shipped in bundles/ must parse with the real parser.
//
// A manifest that does not load is worse than no skill at all: it
// ships, it looks present in review, and it fails at the point where
// somebody is relying on it. The digest check is the sharp end —
// body_sha256 is regenerated by hand when SKILL.md is edited, and
// forgetting is silent until Parse refuses it.
func TestBundledSkillsParse(t *testing.T) {
	t.Parallel()
	root := filepath.Join("..", "..", "bundles")
	if _, err := os.Stat(root); os.IsNotExist(err) {
		t.Skip("no bundles/ directory in this tree")
	}

	var found int
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || info.Name() != "manifest.yaml" {
			return err
		}
		dir, aerr := filepath.Abs(filepath.Dir(path))
		if aerr != nil {
			return aerr
		}
		t.Run(filepath.Base(dir), func(t *testing.T) {
			// Parse requires an absolute dir — the manifest's own
			// handler/body paths are resolved against it, and a
			// relative root would make traversal checks meaningless.
			skill, perr := Parse(dir)
			if perr != nil {
				t.Fatalf("%s does not parse: %v", path, perr)
			}
			if skill.Manifest.Runtime == RuntimeProse && skill.HandlerPath != "" {
				t.Errorf("a prose skill must have no handler path, got %q", skill.HandlerPath)
			}
			if skill.Manifest.Description == "" {
				t.Error("description is what reaches the model; an empty one makes the skill unfindable")
			}
		})
		found++
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if found == 0 {
		t.Error("bundles/ exists but contains no manifests")
	}
}
