// Package embedder is lobslaw's own XLM-RoBERTa text encoder.
//
// WHY OURS. The alternative was depending on aikit, which works well
// and is parity-gated — but is three months old with a single author,
// and this sits on the memory write path. A dependency that goes quiet
// there is not a dependency you can shrug at.
//
// What makes writing it defensible is that the target is FROZEN. BERT /
// RoBERTa / XLM-RoBERTa have not changed since 2018: no GQA, no MoE, no
// RoPE variants, none of the churn that makes a decoder runtime a
// maintenance commitment. The specification we implement against today
// is the one we will implement against in five years.
//
// ONE ARCHITECTURE, THREE MODELS. bge-small (English, 12x384),
// multilingual-e5-base (12x768) and bge-m3 (24x1024, 8k context) are all
// XLMRobertaModel/BertModel with absolute position embeddings, so a
// single forward pass covers all of them and the choice becomes
// configuration rather than code. gte-multilingual was rejected for
// exactly this reason: its "NewModel" architecture is RoPE-based and
// would have been a second code path for no capability we lack.
//
// THE MODEL IS A FILE, NOT AN ASSET. A 250k multilingual vocabulary
// makes the token-embedding table alone ~768 MB at f32, so go:embed is
// off the table — e5-base is 1.1 GB and bge-m3 is 2.2 GB on disk. The
// weights are mmap'd from the data directory. Still entirely local:
// no network at runtime, no sidecar, no API key.
//
// EVERY FAILURE MODE HERE IS SILENT. A tanh GELU where the exact erf
// form was meant; an epsilon outside the sqrt rather than inside; mean
// pooling where the checkpoint declares CLS; an attention scale of
// 1/sqrt(hidden) instead of 1/sqrt(head_dim); a tokenizer that does not
// normalise NFD to NFC. Not one of those crashes. They all just make
// every vector slightly worse, permanently, and the only symptom is
// recall that is a bit off in ways nobody can point at.
//
// So this package is written against a parity gate rather than against
// judgement: see testdata/golden, generated by tools/genfixtures from a
// reference implementation. Token ids are checked as exact integers and
// vectors within tolerance.
package embedder
