package embedder

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// EXACT INTEGERS, NO TOLERANCE.
//
// This is the one gate in the package that admits no approximation. A
// vector can differ in its last bits and still be the same answer; a
// token id cannot. And a tokenizer that is subtly wrong is the worst
// failure available here — it still produces a plausible embedding, so
// nothing downstream notices, and every vector it ever writes is
// quietly for slightly the wrong text.
//
// The fixtures were generated by an independent implementation that is
// itself parity-gated against HuggingFace.
func TestTokenizerMatchesTheReferenceIDs(t *testing.T) {
	g := loadGolden(t)
	dir := modelDir(t)
	tok, err := LoadTokenizer(filepath.Join(dir, "tokenizer.json"))
	if err != nil {
		t.Fatalf("LoadTokenizer: %v", err)
	}
	m, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = m.Close() }()

	for _, f := range g.Fixtures {
		t.Run(f.Note, func(t *testing.T) {
			got := tok.EncodeWithSpecials(f.Text, m.MaxSeq())
			if len(got) != len(f.TokenIDs) {
				t.Fatalf("got %d ids, want %d\n  got  %v\n  want %v\n  text %q",
					len(got), len(f.TokenIDs), got, f.TokenIDs, f.Text)
			}
			for i := range got {
				if got[i] != f.TokenIDs[i] {
					t.Fatalf("id %d differs: got %d, want %d\n  got  %v\n  want %v\n  text %q",
						i, got[i], f.TokenIDs[i], got, f.TokenIDs, f.Text)
				}
			}
		})
	}
}

// The whole pipeline: text in, the reference's vector out. Until this
// passed, Embed could only be called with ids somebody else produced.
func TestEncodeTextReproducesTheReferenceVector(t *testing.T) {
	g := loadGolden(t)
	dir := modelDir(t)
	m, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = m.Close() }()
	tok, err := LoadTokenizer(filepath.Join(dir, "tokenizer.json"))
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range g.Fixtures {
		if len(f.TokenIDs) == 0 {
			continue
		}
		got := m.Embed(tok.EncodeWithSpecials(f.Text, m.MaxSeq()))
		if d := maxAbsDiff(got, f.Vector); d > 1.5e-6 {
			t.Errorf("%s: max abs diff %.3e from reference", f.Note, d)
		}
	}
}

// NFC and NFD spellings of the same word must produce identical ids.
// That is what the Precompiled charsmap is for, and the reason NFKC
// was not substituted for it.
func TestNFCAndNFDTokeniseIdentically(t *testing.T) {
	tok, err := LoadTokenizer(filepath.Join(modelDir(t), "tokenizer.json"))
	if err != nil {
		t.Fatal(err)
	}
	nfc := tok.Encode("café")  // é as one code point
	nfd := tok.Encode("café") // e + combining acute
	if len(nfc) != len(nfd) {
		t.Fatalf("NFC gave %v, NFD gave %v", nfc, nfd)
	}
	for i := range nfc {
		if nfc[i] != nfd[i] {
			t.Fatalf("NFC gave %v, NFD gave %v", nfc, nfd)
		}
	}
}

// The WIDE gate: 115 cases across sixteen scripts plus the awkward
// corners — empty and whitespace-only strings, URLs, paths, code, CJK
// mixed with Latin, full-width forms, ligatures, Roman numerals,
// zero-width and soft-hyphen characters, combining marks, and emoji
// including a ZWJ family sequence.
//
// The vector fixtures cover sixteen cases, which is enough to catch a
// broken forward pass and thin for a tokenizer: a Viterbi wrong only on
// digit runs or mixed-script words would pass them comfortably.
func TestTokenizerMatchesTheReferenceAcrossAWideCorpus(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(fixtureDir(t), "tokens.json"))
	if err != nil {
		t.Fatalf("read token fixtures: %v", err)
	}
	var cases []struct {
		Text string  `json:"text"`
		IDs  []int32 `json:"ids"`
	}
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatal(err)
	}
	if len(cases) < 100 {
		t.Fatalf("only %d token cases; the wide gate has been narrowed", len(cases))
	}
	tok, err := LoadTokenizer(filepath.Join(modelDir(t), "tokenizer.json"))
	if err != nil {
		t.Fatal(err)
	}

	var failed int
	for _, c := range cases {
		got := tok.Encode(c.Text)
		if len(got) != len(c.IDs) {
			failed++
			t.Errorf("%q: got %d ids, want %d\n  got  %v\n  want %v", c.Text, len(got), len(c.IDs), got, c.IDs)
			continue
		}
		for i := range got {
			if got[i] != c.IDs[i] {
				failed++
				t.Errorf("%q: id %d differs\n  got  %v\n  want %v", c.Text, i, got, c.IDs)
				break
			}
		}
	}
	t.Logf("%d/%d token cases exact", len(cases)-failed, len(cases))
}
